# docker-compose.yml

services:
  frontend:
    build:
      context: ./apps/frontend
    container_name: stryve-frontend
    ports:
      - "8081:8081"  # Metro bundler port
    working_dir: /app
    volumes:
      - ./apps/frontend:/app        # Mount source code
      - /app/node_modules           # Avoid overwriting installed node_modules
    command: sh -c "CI=0 npx expo start --lan"
    #changed from --tunnel to --lan 15/12/2025 6:09 AM @Sult9n0-0
    #tunnel isnt working we changed it to lan for now but it works